### PR TITLE
update material design version

### PR DESCRIPTION
**Pull request by javamind**

### CODE REVIEW

**Comment by javamind** [comment]
link to #85

**Comment by clacote** [comment]
Let me know when this tentative fixed is deployed somewhere to test in on iOS.

Also, you seem to struggle with Github keywords for closing/mentionning issues and PR. Here is your new Bible: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by javamind** [comment]
The simplest way is to merge the PR and test on  staging env

**Comment by javamind** [comment]
You can test

**Comment by clacote** [comment]
Where? URL or is doesn't exist.
I didn't follow you workflow and I have no idea where are your test/prod environments you keep talking about.

**Pull request merged**
